### ISSUE TITLE
Roster Editor - Edit Force

### ISSUE THREAD

**Issue by cartag** [BSData/bsdata#100]
__Build 10__
__Roster Editor__

Existing force choices are not showing up after you Edit forces. After adding one after roster exists already, cannot remove because it says it requires at least one.
![image](https://cloud.githubusercontent.com/assets/4388344/12500729/f18f25b2-c072-11e5-92a8-06440ba34295.png)

**Comment by Jonskichov** [comment]
The dumb thing here is that I noticed this before I put out the alpha... Then forgot about it...

Fixed it today, will be in the next build.

**Comment by amis92** [comment]
Okay I may sound harsh, bit I don't think bsdata is the right repo for opening issues of BattleScribe.

If there is a push for GitHub from both @Jonskichov and us (and I guess there is) then maybe a separate repo for battlescribe (even just for issues) shall be created. It just really doesn't fit with data site's repository. I do understand that that's seemingly the best place. I just disagree. Soon we may have more people opening BattleScribe issues there, as they see these now and think 'oh, so that's the place for it'.

All right, rant over. :)

**Comment by Jonskichov** [comment]
@amis92 not harsh! Entirely sensible. I'll make a new repo for alpha bug tracking. I was lazy and just dumped it the existing repo that made most sense, my bad!

**Comment by Jonskichov** [comment]
Moved here: https://github.com/BattleScribe/Alphas/issues/9
