### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by sunabe** [BSData/bsdata#118]
Hi

I would like to join to add files for Dropzone Commander and maybe later for Dropfleet Commander.
https://github.com/sunabe/Dropzone-Commander

in kind regard

sunabe

**Comment by amis92** [comment]
Hi @sunabe,

Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:

1. I create new repository for given game system (https://github.com/BSData/dropzone-commander)
2. I invite you to our organization
3. You accept the invitation and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

**Please read carefully**:
As this is a new repository, please read Developer Guide linked above very carefully. I've looked at your repo you've linked - there are some differences you need to make for this one: save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Also you may join our Wh40k team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) - it's very active and you can ask for some datafile-oriented help if needed.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.
