### ISSUE TITLE
Join BSdata request

### ISSUE THREAD

**Issue by zpettichord** [BSData/bsdata#121]
Hello,

I would like to join bsdata.

Thank you!
Zach

**Comment by amis92** [comment]
Hello, I'd just like to make sure you want to help develop data files, since you've omitted any description?

1. If you just want to use datafiles, there's no need for you to join. Just use the website: [BattleScribe Data on Appspot](http://battlescribedata.appspot.com/#/repos).

2. On the other hand, if you'd like to help us develop datafiles, please post the Join Request in appropriate repo (list is here: https://github.com/BSData/bsdata/wiki#getting-started).

3. If you actually want to help develop the AppSpot website that this repo is for, please state the intent clearly, there were (up to this point) no volunteers for it.
