### ISSUE TITLE
BSData Join Request

### ISSUE THREAD

**Issue by gunnersberry** [BSData/bsdata#147]
Hi guys, love the app, thank you for all your hard work.

I'm interested in creating a modified Heresy version of Shadow Wars for personal use while learning Git - if I'm comfortable with what I produce, and it's of a good quality, then obviously I'd be happy to share it.

Thanks!
Josh

**Comment by gunnersberry** [comment]
Hi @amis92, 

Can I now start creating the file?

Thanks,
Josh

**Comment by amis92** [comment]
I've not had time 'til now to respond, sorry.

We do not happily host "fan"-made systems. An exception was made for Heralds of Ruin killteam because of the traction it had at that moment - and now it's close to unused after Shadow Wars was released.

So of course, go on - write your file. But don't hold your breath on us. If your idea gains spectacular support, by all means we'll gladly host the files. Until then, not so much. Also, I'm not the only decisive person. I suggest you ask on Horus Heresy gitter chat, maybe those guys will be more supportive :)

**Comment by gunnersberry** [comment]
No worries Amadeusz, thanks for getting back to me.

Appreciate you can't just host any file that someone feels like creating
for fun. I'll happily host it myself in the meantime unless it's super
popular among the heresy crowd :)

Appreciate the heads up about the Horus Heresy guys on gitter chat, I'll
get in touch with them.

Thanks and have a great weekend!
Josh
