### ISSUE TITLE
New data: A Song of Fire and Ice Miniature Game

### ISSUE THREAD

**Issue by lsmassa** [BSData/bsdata#155]
Hi,

I just finish the first version of the data files for the game A Song Of Fire and Ice Miniature Game, currentily in Kickstarter.
I'd like to add it to the repositories drive to share with all.
Could you help me?

Thanks

Lucas
[asong.zip](https://github.com/BSData/bsdata/files/1220252/asong.zip)

**Comment by amis92** [comment]
Hi @lsmassa ,

in general, if you want to provide new game system's files, the procedure is as follows:

1. I create new repository for given game system
2. I invite you to our organization
3. You accept the invitation and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Are you still interested? Should I send you an invite?

Amis

**Comment by lsmassa** [comment]
Hi Amis,

Yes, I'm still interested.
Don't worry, I'll keep the updates.
Maybe I'll need some help only to make sure that I'm doing all correctley,
because it's the first data files that I made.

Thanks,

Lucas Massa


2017-08-17 12:22 GMT-03:00 Amadeusz Sadowski <notifications@github.com>:

**Comment by amis92** [comment]
Hi @lsmassa,

Please accept the invitation in the email or on the [repo page](https://github.com/BSData/song-of-ice-and-fire/invitations). Welcome aboard!

That's the repo: https://github.com/BSData/song-of-ice-and-fire

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

**Please read carefully**:
As this is a new repository, please read Developer Guide linked above very carefully. I've looked at your repo you've linked - there are some differences you need to make for this one: save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Also you may join our Wh40k team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) - it's very active and you can ask for some datafile-oriented help if needed.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

**Comment by lsmassa** [comment]
Amis,

Thanks for the information, I'll read all very carefully.
However, I stuck in the beginning of it, because when I open the GitHub
Desktop, the BSDATA doesn't show in the list.



2017-08-17 13:15 GMT-03:00 Amadeusz Sadowski <notifications@github.com>:

**Comment by amis92** [comment]
A lot has changed in UI since the tutorials were done, so you need to adapt :)

As an alternative, you can try on the web:

![2017-08-17 2](https://user-images.githubusercontent.com/2671396/29433097-376e1b0c-839e-11e7-9a35-b70eb700b073.png)

That should request to open GitHub Desktop and start cloning the repo there.
