### ISSUE TITLE
Change non-local information

### ISSUE THREAD

**Issue by M-J-Hastings** [BSData/bsdata#161]
Hello,

I do not know and cannot see how to change/create non-local information such as Profiles and Rules.

Can someone point me in the correct direction please.

Thanks,

Matt H

**Comment by XWingDrLucky** [comment]
Ever since the upgrade to 2.X, we've been able to put anything (entries, rules, profiles, etc) in the GST file rather than in individual CAT files.  That's helpful if the same unit/upgrade/rule appears in more than one faction's army list for your game system.  If you are editing a catalogue and something is showing as non-local, it means that item is actually in the game system file (and thus accessible to all catalogues built on that game system).  Understand that changing it in the GST will affect all catalogues.

**Comment by M-J-Hastings** [comment]
Perfect. Yes that's an extremely helpful and thoughtful tool and I will of course be careful in what I add or change (mainly annoying typos!).

Thank you for the help.
