### ISSUE TITLE
Join Request - Warzone Resurrection

### ISSUE THREAD

**Issue by DarthFraggle** [BSData/bsdata#175]
I'm working on a file for Warzone Resurrection. I've got most of the factions in already. 
https://github.com/DarthFraggle/Warzone-Resurrection-Battlescribe

**Comment by DarthFraggle** [comment]
Sorry, this is the current link:
[(https://github.com/DarthFraggle/Warzone-Resurrection-2.2)]

I'm new with github and this is my first battlescribe file. I'm having touble getting it to work. I send myself the github link on another computer and I'm unable to download the repository. What am I missing?

**Comment by amis92** [comment]
You were having bad format for URLs in text, I've fixed that.

Hi @DarthFraggle ,

in general, if you want to provide new game system's files, the procedure is as follows:

1. I create new repository for given game system
2. I invite you to our organization
3. You accept the invitation and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Are you still interested? Should I send you an invite?

Amis

PS You cannot easily connect normal repository to battlescribe, so that's why it's not working for you. It's still not a supported scenario.

**Comment by DarthFraggle** [comment]
Yes, I'm still interested, and I was intending to maintain the file. Thanks for your help.

**Comment by amis92** [comment]
Hi @DarthFraggle ,

Please accept the invitation in the email or on the [repo webpage](https://github.com/BSData/warzone-resurrection/invitations). Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system (https://github.com/BSData/warzone-resurrection)
2. I invite you to our organization
3. You accept the invitation and gain push/write access to this new repository
4. You upload files and maintain them if possible.

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

**Please read carefully**:
As this is a new repository, please read Developer Guide linked above very carefully. I've looked at your repo you've linked - there are some differences you need to make for this one: files should be put directly in repo folder (you have a subfolder).
BTW (if you had that idea) you also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.
