### ISSUE TITLE
BattleScribe Data for The Genesys Project

### ISSUE THREAD

**Issue by Lionhammer** [BSData/bsdata#178]
Hi,

I came here for a request for experienced coders to make a Data file for [The Genesys project](http://www.thegenesysproject.com/) from Faeit 212. It's a custom wargame where you can create your own army with different traits and weapons and play both with and without campaign. The game is still in beta and receiving feedback from playtesters.
I believe that creating a Data file for the game will help new players to get in the project and making it easier to build an army and play.

I hope you guys take a look at it and decide to create it for BattleScribe.

Lionhammer

**Comment by amis92** [comment]
That doesn't work like that. When there is someone interested in making files, and they do them, only at that point we can help. There is no "task force" of coders, 99% of us are non-programming people who just happen to wish to sacrifice some of their free time on datafiles for the game they play. So unless there comes someone with the files and asks to have them hosted, well, there won't be any.

Amis

PS Creating these files is really not that hard, there is a bundled Data Editor in desktop version of BS; maybe you can give it a shot, or you know someone who might want to.

PPS I'm closing the issue because currently there won't be any further action, but feel free to answer, ask or otherwise express yourself.
