### ISSUE TITLE
Legends of the Old West

### ISSUE THREAD

**Issue by Atr0k** [BSData/bsdata#181]
Hi,

I've created data files for Legends of the Old West, and old Warhammer Historical game. How are you handling the new repo creation and such?

**Comment by amis92** [comment]
Hi @Atr0k,

in general, if you want to provide new game system's files, the procedure is as follows:

1. I create new repository for given game system
2. I invite you to the repo
3. You accept the invitation and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Are you still interested? Should I send you an invite?

Amis

**Comment by Atr0k** [comment]
Yes, sure, maintaining a repository shouldn't be a hard task. Thank you!

**Comment by amis92** [comment]
Hi @Atr0k,

Please accept the invitation in the email or on the [repo webpage](https://github.com/BSData/legends-of-the-old-west/invitations). Welcome aboard!

The repo: https://github.com/BSData/legends-of-the-old-west

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

**Please read carefully**:
As this is a new repository, please read Developer Guide linked above very carefully. Save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.
