### ISSUE TITLE
Battlefleet Gothic

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/bsdata#184]
Hi there, I recently made a lot of improvements on the Battlefleet Gothic data repository, and was wondering how to make a release so my friends can acces it too

thanx, and sorry If Im asking in the wrong place, Im kind of new to Github.

**Comment by amis92** [comment]
Hey there!

I think it'll be easier if I just give you repo write access, so that you can freely manage it. I do however wonder, was creating another `Abbadons Black Crusade` catalogue intentional? Right now one has `BFGXR` suffix and the other doesn't. Also looking at summary of changes since last release, it seems the unsuffixed one had its name changed. Please change it back to how it was originally - otherwise people updating data will get errors. https://github.com/BSData/battlefleetgothic/compare/v1.1...master (Files changed tab).

Are you up to it?

**Comment by Tomakokamikaze** [comment]
The name changing is a bad side effect of my battlescribe attempting to not override its last version. I apologize for it amd will fix it.
The BFGXR is for people who want to use a set of rules created by the BFG community. They differ from the standart BFG rules, so its best not to mix them. If you know a better way of sorting it I would be glad to hear it.

And I am definetly up for the task if you give me repo acces.
Thank you for the opportunity to help improve the game.

**Comment by amis92** [comment]
Hmm. We don't host community rules in general, with very few exceptions (9th Age). If it's a community effort, can it wait a month or two? And also, is only Abbaddon getting community rules?

**Comment by Tomakokamikaze** [comment]
Well, Abbadon is the force I play, therefore the reason I wanted to make Improvements upon it. And I think it could wait, but then again I dont see why.

**Comment by amis92** [comment]
The reason is that there's a plan to enable having separate community repos (think addon/plugin) that just provide catalogues to an existing game system.

That'd make it so you have one repo for official game system, and other repos for unofficial/community extensions - this way those interested can get both, but those that aren't don't have to download unwanted content.

Do you think it'd be ok for this BFGXR to wait until then and be provided in this fashion instead?

**Comment by Tomakokamikaze** [comment]
Sure, i just was not seeing the data volume as an issue since all BFG files are so light up untill now

**Comment by amis92** [comment]
There you go then :) https://github.com/BSData/battlefleetgothic/invitations

**Comment by Tomakokamikaze** [comment]
Thank you, I will not let you down.

**Comment by Tomakokamikaze** [comment]
So, I made a new releae, bit  still cant access it through my phone. anything I should Have done?

**Comment by amis92** [comment]
It takes up to 24 hrs, keep that in mind. Should be available now :)
