### ISSUE TITLE
Repository for Dropfleet Commander

### ISSUE THREAD

**Issue by morvael** [BSData/bsdata#186]
I would like to submit data files for Dropfleet Commander. Can I get a repository for that?

**Comment by amis92** [comment]
Hi @USER,

Please accept the invitation in the email or on the [repo webpage](https://github.com/BSData/dropfleet-commander/invitations). Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system (https://github.com/BSData/dropfleet-commander)
2. I invite you to our organization
3. You accept the invitation and gain push/write access to this new repository
4. You upload files and maintain them if possible.

The important part is that we Organization Admins do not have time to maintain/push/upload files. So unless there is someone else interested, you'll have to do some work to make our website host those files.

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

**Please read carefully**:
As this is a new repository, please read Developer Guide linked above very carefully. Save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.

**Comment by morvael** [comment]
Hi @amis92

I have a few questions:
1) Do I have to push the files as soon as possible? Knowing how hard is to get an answer from BS author, I have created this issue well in advance (after creating working concept of the data files, with one army out of four, this is now expanded to three). You surprised me by creating the repository so quickly. I need a few more days to finish initial version.
2) Are files in repo published automatically, so I have to commit them in working state or is there a publication switch somewhere? I would happily commit what I have now, but it's not ready for distribution.
3) Will I remain in sole control of the files (unless I'll go AWOL), or will you add new contributors without asking me first?

Thanks,
morvael

**Comment by amis92** [comment]
I'd ask you to read Developer Guide linked above and come back with revised list of questions :D

@ 3 - don't worry, unless AWOL I ask repo maintainers (people interested should open issues in given repo).

**Comment by amis92** [comment]
Also, Jon (BS developer) doesn't really handle community here, I do - and I don't develop BattleScribe in turn.

**Comment by morvael** [comment]
@amis92, thanks for pointing me to the guide, somehow I read only the first part about setting up "dev environment".

I wish Jon was less elusive, or (at least) that there would be a dedicated bug reporting tool for BS. Currently bug reports have to go to uservoice wishlist and become drowned in hundreds of good ideas posted there (but "only" ideas), and one has to spend one of the precious votes on them. I'm pretty sure there is a bug in BS, where it's not able to calculate how many points given entry costs (including cost of subentries) for the purposes of a constraint (which works otherwise, because by switching "maximum" to "minimum" I get a report which shows correct limit and 0 entry value). "Selection" constraints work correctly. It also occurs to me that counting entries work, but counting categories do not (IMHO it should work by counting entries that have given category) - but I have worked around this by using entries. The first issue is however a blocker.

**Comment by amis92** [comment]
There is a special bureport repo for dataauthors, now that you've joined us I can give you this very secretive link ;) Do not share with non-data-authoring community, though. It really is for data-author reports only. https://github.com/BattleScribe  - there you have a repo for release bugs, and those from beta, which it probably is not in your case.

**Comment by morvael** [comment]
@amis92 Thanks a lot for that link. I made two bug reports with test cases. I hope they will be looked at.
