### ISSUE TITLE
I would like to join the BSData team

### ISSUE THREAD

**Issue by Tigerwraith** [BSData/bsdata#197]
I'm working on data files for CAV:SO (Combat Assault Vehicle: Strike Operations) I'm still in the beginning stages of creation, but I have a couple of people that want to help out. Please let me know what I need to do to get my project added. 

Thanks

**Comment by amis92** [comment]
Hi @Tigerwraith,

Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

In general, if you want to provide new game system's files, the procedure is as follows:
1. I create new repository for given game system (https://github.com/BSData/cav-strike-operations)
2. I invite you to the repo
3. You accept the invitation and gain push/write access to this new repository
4. You upload files and maintain them if possible.

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

**Please read carefully**:
As this is a new repository, please read Developer Guide linked above very carefully. I've looked at your repo you've linked - there are some differences you need to make for this one: save all files in unzipped format (`.cat` instead of `.catz` and `.gst` instead of `.gstz`); you can achieve this using `File`->`Save as` and choosing the correct format from dropdown under filename.
You also shouldn't put any index files (`index.xml` or `index.bsi`), the website on AppSpot does indexing automatically.

Cheers!
Amis

PS You can always `@mention` me by writing `@amis92` in your issue comment, and I'll try to help you out.
