### ISSUE TITLE
Age of Sigmar in Spanish

### ISSUE THREAD

**Issue by petreopatroklos** [BSData/bsdata#199]
Hi! I already translated Age of Sigmar repository to spanish.

How can I apear on main list?

https://github.com/petreopatroklos/Git-AOS/commit/1694edfe4da92b73b6d9fc8bde930994ecc7347d#diff-272e8fe6c0bcf7b85a6b02f534967a8f

Thanks

**Comment by amis92** [comment]
@petreopatroklos I'm rather negative on that. BattleScribe doesn't support translations. I'm really sorry, because translating everything there was certainly a lot of work. However, unless you have some kind of an automatic tool, your datafiles will quickly become desynchronized with the originals - there's small chance you'd keep up with the amount of work a good couple of people do there.

I'm open to further discussion, though. Maybe you have some interesting solutions?

**Comment by amis92** [comment]
Closed in favour of referenced issue.
