### ISSUE TITLE
Warhammer Diskwars Data... ready to upload!

### ISSUE THREAD

**Issue by MFFDM** [BSData/bsdata#60]
Hi!

I've created a data for Warhammer Diskwars a FFG game. If you don't know about the game... http://boardgamegeek.com/boardgame/146418/warhammer-diskwars

The data is finished and I want upload it to BS repo, how do i do it?

Thanks!

**Comment by amis92** [comment]
Well, you've done exactly what's needed, you asked. :) Now as an Admin I create the repo...

...and done! I'll invite you to the organisation, so that you will be able to upload files. I guess you've read Wiki here, so you probably know how to use GitHub etc. You'll need to accept the invitation though!

The new repo: https://github.com/BSData/warhammer-diskwars

**Comment by MFFDM** [comment]
I think that I released the data correctly, but... How can users add the repo on BS?

**Comment by amis92** [comment]
Through http://battlescribedata.appspot.com/#/repos of course. However, the site needs up to few hours until it shows up (refreshes).

**Comment by MFFDM** [comment]
Thanks!!
