### ISSUE TITLE
Star Wars: Armada New Repo Req

### ISSUE THREAD

**Issue by BrianisBlack** [BSData/bsdata#66]
Hi!  I've started working on a fileset for Star Wars: Armada.  Can this get added as a new repo with me as a dev?

Thanks!
Brian

**Comment by amis92** [comment]
Sure. I hope you've read our wiki pages, but anyway, ask if you've got more questions. Here's your new repo. You'll be granted write access after you accept invitation to BSData organisation. You'll become member of 'other' dev group. Cheers!

PS here's your new repo: https://github.com/BSData/star-wars-armada

**Comment by BrianisBlack** [comment]
I've been reading the wiki pages, and while I think I understand editing existing repos, I'm not entirely certain which files need to be pushed to start a new one.  

Right now I've thrown all of the files generated by the BS Data Indexer into the repo, but on comparing to the swxwing repo (which has the same rough structure), only the catalogue and game system files are hosted. This doesn't seem to make the files available on the main app spot page so I'm sure I'm doing something wrong here. 

Additionally, those are .cat and .gst files, rather than .catz and .gstz, which fileset should I use?  Should I literally just be copying the .cat and .gst files to my local clone then pushing that to the server?

Sorry for all the questions!

**Comment by amis92** [comment]
Ok, so:
1. `.catz`, `.gstz` - those are zipped files. Not to be used in GitHub repos. You need to `File`>`Save as...` and choose appropriate (non *z) format. This will create unzipped clone, you can delete zipped one. Do that with every catalogue and game system.
2. Only those files (catalogues and game system) are required. Index is created by AppSpot application automatically and is hosted on AppSpot only.
3. AppSpot lists only repositories which contain single `.gst` file, that's why the repo is currently not listed. Additionaly I'll remind you of development cycle: https://github.com/BSData/bsdata/wiki/Developer-Guide#development-cycle - don't forget to make release. :)

As for copying - when you cloned the repo in GitHub app, it probably asked you to choose destination. If you select `BattleScribe/data`, you'll have those files available in BattleScribe GameSystem/Catalogue/Roster editors. (If you cloned into different folder, just delete the repo and clone again).

Please don't hesitate to ask further.

**Comment by BrianisBlack** [comment]
Gotcha, I'll give this another go.  Thanks!

**Comment by BrianisBlack** [comment]
Alright, looks like I've got myself setup properly.  Thanks for your assistance @amis92!
