### ISSUE TITLE
Little confused with release

### ISSUE THREAD

**Issue by JimmyMalmer** [BSData/bsdata#81]
@amis92

Edit: I am the new lead dev for the 9th age files, and I am trying to get set up.

I read up on the release procedure, and I have 2 questions:

If I commit to master, it should automatically pop up without having to make an official release. Is this correct?

I commited to master AND taged a release on the latest commit. Still it doesn't pop up on Appspot. Is that because you will manually set it up, and have not yet done so? I would like to get it up there for our users asap.

I am using git bash rather than the UI crap as that is what I'm used to. I cant see how it would make any difference, but I might have missed something.

Thanks
Jimmy

**Comment by XWingDrLucky** [comment]
You have to actually issue the releases.  Just committing the changes will make them show up on GitHub, but issuing the release is what pushes them to the Appspot page.

For some reason, there does seem to be a delay between issuing the release and the new version showing up on Appspot.  It used to be about 15 minutes but it seems like it has been a few hours for the last few releases I've done.  I'm not sure why.

I am seeing your files on the Appspot page with just the initial release, so hopefully your subsequent releases start popping up soon.

**Comment by JimmyMalmer** [comment]
Alright. I only did 1 release, and it seems to work fine. However, I read in the instructions that pushing to master should do it. This is of relevance, because it means that we cannot push half-done work to master.

**Comment by XWingDrLucky** [comment]
Just committing changes to the master will not push them out to the file
hosted on Appspot. I've had a commit with a single tiny typo correction
during around for three+ weeks. It is in the master file on GitHub and
anyone who syncs or edits the file will see it. However, regular users who
simply download data for Battlescribe won't get it because it hasn't been
released yet and isn't yet part of the repository on the Appspot page. Only
when I issue a new release will it become part of the public version.

You can commit unfinished work without it being distributed. Just don't
release the unfinished work.

**Comment by JimmyMalmer** [comment]
Cool. Thank you. Then we know how to use it.
