### ISSUE TITLE
Data Editor - No Shared Entry Groups

### ISSUE THREAD

**Issue by cartag** [BSData/bsdata#95]
__Build 10__
__Data Editor__
* Data files still on 1.15 format will load without any Shared Entry Groups. Have checked three different files, all have blank Shared Groups. 
![image](https://cloud.githubusercontent.com/assets/4388344/12499986/4f73c7fc-c06c-11e5-8a61-f0b531bdb354.png)

**Comment by cartag** [comment]
I made a new data file to see how they are labeled. In 1.15.X, the Shared Selection Entry Groups  were labeled under __sharedSelectionGroupEntries__, where under 1.16 they are under __sharedSelectionEntryGroups__

In 1.15.X
![image](https://cloud.githubusercontent.com/assets/4388344/12520918/9989957c-c104-11e5-8d54-5e6d9ce742f7.png)

In 1.16
![image](https://cloud.githubusercontent.com/assets/4388344/12520927/a6a634fe-c104-11e5-96eb-a528ccd555fd.png)

**Comment by cartag** [comment]
Manually renaming in Notepad from 1.15 to current 1.16 label makes them show up.

![image](https://cloud.githubusercontent.com/assets/4388344/12521072/99a778d4-c105-11e5-9ccc-ce354de7e168.png)

**Comment by Jonskichov** [comment]
This was a typo - it should be selectionEntryGroups (in line with selectionEntries). 

New naming convention is xxxEntry, or xxxEntryGroup for groups thereof, where the xxx is the name of the appropriate roster XML element.

E.g.
SelectionEntry -> Selection 
ForceEntry -> Force

Etc...

This issue was a typo... :/

Revert to 1.15.x data, and let it update again. You should be good to go. (Let me know otherwise)

**Comment by cartag** [comment]
Will it convert the old format to the new, or will we have to recreate everything? If I have to run a dual install of 1.15 and 1.16 I will just to get things transferred over if not, it will be a huge undertaking though. 

If we'd have to recreate everything, I can write up a conversion walkthrough for others to do what I did to get them to show.

**Comment by Jonskichov** [comment]
It will update 1.15 files to the 1.16 format automatically. This issue was due to a bug in the update process (more specifically the XSL stylesheet). This means you need to go back to the 1.15 data and let it go through the upgrade process again.

The only thing you may need to do by hand is some root level "in parent" constraint changes. This _could_ be done by the XSL in theory, but looks like it would be very taxing - or mould take way to long on mobile.
