### ISSUE TITLE
Data Editor - Validation Errors

### ISSUE THREAD

**Issue by cartag** [BSData/bsdata#98]
__Build 10 Bug report__
__Data Editor__
* Not sure what changed between builds 9 and 10, but in 9 I had eight validation errors total, all dealing with the Legacy of Ruin point limits. Same data file now gives me a huge string of them. Not sure what the difference was, but there are a lot of conditions. Some of this is caused by the missing Shared Entry Groups, most of it is not.  
![image](https://cloud.githubusercontent.com/assets/4388344/12500294/f9dc4fd2-c06e-11e5-8609-3101ba638a3e.png)

**Comment by Jonskichov** [comment]
Did you revert your data?

You'll need to go back to the 1.15.x data and start over...

**Comment by cartag** [comment]
I never saved any changes after installing Build 9 on. All files are in the same condition they were in before hand.

**Comment by Jonskichov** [comment]
It will update 1.15 files to the 1.16 format automatically. This issue was due to a bug in the update process (more specifically the XSL stylesheet). This means you need to go back to the 1.15 data and let it go through the upgrade process again.

The only thing you may need to do by hand is some root level "in parent" constraint changes. This _could_ be done by the XSL in theory, but looks like it would be very taxing - or mould take way to long on mobile.

[ Copied/pasted from another issue :) ]
